### ISSUE TITLE
本番環境でログインできない

### ISSUE THREAD

**Issue by pekorinko** [pekorinko/review_check#104]
- 本番環境用に作成したclient_idとclient_secretを`EDITOR=vim bin/rails credentials:edit`を実行して`config/credentials.yml.enc`に暗号化して保存した
  - 結果、 `there's nothing here yet`が表示される
```
【config/credentials.yml.enc】
# aws:
#   access_key_id: ******
#   secret_access_key: ********

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: *********************
github:
 client_id: "***********************"
 client_secret: "***********************"
 client_id_dev: "***********************"
 client_secret_dev: "***********************"
```
- 環境変数でclient_idとclient_secretを渡す仕様に変更したが `there's nothing here yet`が表示される
```
【config/initializers/omniauth.rb】
Rails.application.config.middleware.use OmniAuth::Builder do
  if Rails.env.development? || Rails.env.test?
    provider :github,
             Rails.application.credentials.github[:client_id_dev],
             Rails.application.credentials.github[:client_secret_dev]
  else
    provider :github,
             #  Rails.application.credentials.github[:client_id],
             #  Rails.application.credentials.github[:client_secret],
             ENV['GITHUB_CLIENT_ID'],
             ENV['GITHUB_CLIENT_SECRET']
  end
end
```
- 関連issue https://github.com/pekorinko/review_check/issues/93
