### ISSUE TITLE
mainデプロイ用で作ったOAuth Appsの`client_id`と`client_secret`は以下に書く認識で合っているか

### ISSUE THREAD

**Issue by pekorinko** [pekorinko/review_check#93]
## 6/5（土）の画面共有の際に本番環境用にOAuth Appsを新たに作成した
- 本番環境のclient_idとclient_secretを記載する必要がある
```
【config/initializers/omniauth.rb】
Rails.application.config.middleware.use OmniAuth::Builder do
  if Rails.env.development? || Rails.env.test?
    provider :github,
             Rails.application.credentials.github[:client_id_dev],
             Rails.application.credentials.github[:client_secret_dev]
  else
    provider :github,
             Rails.application.credentials.github[:client_id],
             Rails.application.credentials.github[:client_secret]
  end
end
```
### `EDITOR=vim bin/rails credentials:edit`を実行して`config/credentials.yml.enc`に暗号化して保存してある`client_id``client_secret`を書き換える
- 現状、`client_id:`と`client_id_dev`, `client_secret_dev`と`client_secret`の内容が同じ（いずれも開発用に作成したIDとシークレットのまま）
```
# aws:
#   access_key_id: ******
#   secret_access_key: ********

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: *********************
github:
 client_id: "***********************"
 client_secret: "***********************"
 client_id_dev: "***********************"
 client_secret_dev: "***********************"
```
